version : '3.8'

services:
  api:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_USER: admin
      MYSQL_DATABASE: LLMBD
      MYSQL_USER: user
      MYSQL_PASSWORD: user
